CC=emcc

CFLAGS=-Wall -Wpedantic -std=c99 -s USE_SDL=2 -s ALLOW_MEMORY_GROWTH=1

LDLIBS=-lSDL2

EXE =   index.html

OBJ =   jc_reborn.o \
        utils.o \
        uncompress.o \
        resource.o \
        dump.o \
        story.o \
        walk.o \
        calcpath.o \
        ads.o \
        ttm.o \
        island.o \
        bench.o \
        graphics.o \
        sound.o \
        events.o \
        config.o


all: $(EXE)

$(EXE): $(OBJ)

clean:
	rm -v $(OBJ) $(EXE) 2> /dev/null ; true

