/* Auto-generated by scripts/generate-restore-pilots-header.py */
#ifndef PS1_RESTORE_PILOTS_H
#define PS1_RESTORE_PILOTS_H

#include "mytypes.h"

struct TPs1RestorePilotRect {
    uint16 x;
    uint16 y;
    uint16 width;
    uint16 height;
};

struct TPs1RestorePilotTtm {
    const char *ttmName;
    uint16 clearRegionId;
    uint16 saveImageRegionId;
    struct TPs1RestorePilotRect rect;
};

struct TPs1RestorePilot {
    const char *adsName;
    uint16 selectedAdsTag;
    uint16 sceneIndex;
    struct TPs1RestorePilotRect unionRect;
    uint16 adsTagCount;
    const uint16 *adsTags;
    uint16 rectCount;
    const struct TPs1RestorePilotRect *rects;
    uint16 ttmCount;
    const struct TPs1RestorePilotTtm *ttms;
};

static const uint16 gPs1RestorePilot0AdsTags[3] = { 1u, 2u, 3u };

static const struct TPs1RestorePilotRect gPs1RestorePilot0Rects[2] = {
    { 248u, 196u, 344u, 139u },
    { 256u, 197u, 344u, 139u },
};

static const struct TPs1RestorePilotTtm gPs1RestorePilot0Ttms[2] = {
    { "MJAMBWLK.TTM", 0u, 0u, { 248u, 196u, 344u, 139u } },
    { "MJTELE.TTM", 0u, 0u, { 256u, 197u, 344u, 139u } },
};

static const struct TPs1RestorePilot gPs1RestorePilot0 = { "STAND.ADS", 1u, 38u, { 248u, 196u, 352u, 140u }, 3u, gPs1RestorePilot0AdsTags, 2u, gPs1RestorePilot0Rects, 2u, gPs1RestorePilot0Ttms };

static const uint16 gPs1RestorePilot1AdsTags[1] = { 1u };

static const struct TPs1RestorePilotRect gPs1RestorePilot1Rects[5] = {
    { 224u, 90u, 160u, 134u },
    { 0u, 147u, 448u, 203u },
    { 192u, 199u, 264u, 142u },
    { 144u, 87u, 384u, 152u },
    { 0u, 199u, 312u, 151u },
};

static const struct TPs1RestorePilotTtm gPs1RestorePilot1Ttms[4] = {
    { "MEANWHIL.TTM", 0u, 65535u, { 224u, 90u, 160u, 134u } },
    { "SJMSSGE.TTM", 0u, 0u, { 0u, 147u, 448u, 203u } },
    { "SJWORK.TTM", 0u, 0u, { 192u, 199u, 264u, 142u } },
    { "THEEND.TTM", 0u, 0u, { 144u, 87u, 384u, 152u } },
};

static const struct TPs1RestorePilot gPs1RestorePilot1 = { "JOHNNY.ADS", 1u, 25u, { 0u, 87u, 528u, 263u }, 1u, gPs1RestorePilot1AdsTags, 5u, gPs1RestorePilot1Rects, 4u, gPs1RestorePilot1Ttms };

#define PS1_RESTORE_PILOT_COUNT 2u

static const struct TPs1RestorePilot gPs1RestorePilots[PS1_RESTORE_PILOT_COUNT] = {
    gPs1RestorePilot0,
    gPs1RestorePilot1,
};

#endif
