#!/usr/bin/env python3
"""Generate a combined C header from one or more restore pilot specs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


DEFAULT_SPECS = [
    Path("docs/ps1/research/restore_pilot_spec_2026-03-18.json"),
    Path("docs/ps1/research/restore_pilot_spec_johnny_2026-03-18.json"),
    Path("docs/ps1/research/restore_pilot_spec_walkstuf_2026-03-18.json"),
]
DEFAULT_HEADER = Path("ps1_restore_pilots.h")


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def save_image_region_id(row: dict) -> int:
    region_ids = row.get("clear_region_ids") or [0]
    op_counts = row.get("op_counts") or {}

    # When the script already commits its own background slice via COPY_ZONE_TO_BG,
    # the SAVE_IMAGE1 pilot hook tends to fight that baseline and leaves black cards.
    if op_counts.get("copy_zone_to_bg", 0) > 0:
        return 0xFFFF

    return int(region_ids[0])


def build_header(specs: list[dict]) -> str:
    lines = [
        "/* Auto-generated by scripts/generate-restore-pilots-header.py */",
        "#ifndef PS1_RESTORE_PILOTS_H",
        "#define PS1_RESTORE_PILOTS_H",
        "",
        "#include \"mytypes.h\"",
        "",
        "struct TPs1RestorePilotRect {",
        "    uint16 x;",
        "    uint16 y;",
        "    uint16 width;",
        "    uint16 height;",
        "};",
        "",
        "struct TPs1RestorePilotTtm {",
        "    const char *ttmName;",
        "    uint16 clearRegionId;",
        "    uint16 saveImageRegionId;",
        "    struct TPs1RestorePilotRect rect;",
        "};",
        "",
        "struct TPs1RestorePilot {",
        "    const char *adsName;",
        "    uint16 selectedAdsTag;",
        "    uint16 sceneIndex;",
        "    struct TPs1RestorePilotRect unionRect;",
        "    uint16 adsTagCount;",
        "    const uint16 *adsTags;",
        "    uint16 bmpCount;",
        "    const char *const *bmps;",
        "    uint16 scrCount;",
        "    const char *const *scrs;",
        "    uint16 sceneTtmCount;",
        "    const char *const *sceneTtms;",
        "    uint16 rectCount;",
        "    const struct TPs1RestorePilotRect *rects;",
        "    uint16 ttmCount;",
        "    const struct TPs1RestorePilotTtm *ttms;",
        "};",
        "",
    ]

    for idx, spec in enumerate(specs):
        selected = spec["selected_scene"]
        rect = spec["restore_template"]["union_rect"]
        rects = spec["restore_template"]["unique_rects"]
        ttm_details = spec["ttm_details"]
        ads_tags = spec["recommended_runtime_scope"]["ads_tags"]
        scene_resources = spec["scene_resources"]
        prefix = f"gPs1RestorePilot{idx}"

        lines.append(f"static const uint16 {prefix}AdsTags[{len(ads_tags)}] = {{ {', '.join(f'{tag}u' for tag in ads_tags)} }};")
        lines.append("")
        lines.append(f"static const char *const {prefix}Bmps[{len(scene_resources['bmps'])}] = {{")
        for name in scene_resources["bmps"]:
            lines.append(f"    {c_string(name)},")
        lines.append("};")
        lines.append("")
        lines.append(f"static const char *const {prefix}Scrs[{len(scene_resources['scrs'])}] = {{")
        for name in scene_resources["scrs"]:
            lines.append(f"    {c_string(name)},")
        lines.append("};")
        lines.append("")
        lines.append(f"static const char *const {prefix}SceneTtms[{len(scene_resources['ttms'])}] = {{")
        for name in scene_resources["ttms"]:
            lines.append(f"    {c_string(name)},")
        lines.append("};")
        lines.append("")
        lines.append(f"static const struct TPs1RestorePilotRect {prefix}Rects[{len(rects)}] = {{")
        for row in rects:
            lines.append(f"    {{ {row['x']}u, {row['y']}u, {row['width']}u, {row['height']}u }},")
        lines.append("};")
        lines.append("")
        lines.append(f"static const struct TPs1RestorePilotTtm {prefix}Ttms[{len(ttm_details)}] = {{")
        for row in ttm_details:
            region_ids = row.get("clear_region_ids") or [0]
            union_rect = row["union_rect"]
            save_region_id = save_image_region_id(row)
            lines.append(
                "    { "
                + c_string(row["ttm_name"])
                + f", {region_ids[0]}u, {save_region_id}u, "
                + "{ "
                + f"{union_rect['x']}u, {union_rect['y']}u, {union_rect['width']}u, {union_rect['height']}u"
                + " } },"
            )
        lines.append("};")
        lines.append("")
        lines.append(
            f"static const struct TPs1RestorePilot {prefix} = "
            + "{ "
            + c_string(selected["ads_name"])
            + f", {selected['ads_tag']}u, {selected['scene_index']}u, "
            + "{ "
            + f"{rect['x']}u, {rect['y']}u, {rect['width']}u, {rect['height']}u"
            + " }, "
            + f"{len(ads_tags)}u, {prefix}AdsTags, "
            + f"{len(scene_resources['bmps'])}u, {prefix}Bmps, "
            + f"{len(scene_resources['scrs'])}u, {prefix}Scrs, "
            + f"{len(scene_resources['ttms'])}u, {prefix}SceneTtms, "
            + f"{len(rects)}u, {prefix}Rects, {len(ttm_details)}u, {prefix}Ttms"
            + " };"
        )
        lines.append("")

    lines.append(f"#define PS1_RESTORE_PILOT_COUNT {len(specs)}u")
    lines.append("")
    lines.append(f"static const struct TPs1RestorePilot gPs1RestorePilots[PS1_RESTORE_PILOT_COUNT] = {{")
    for idx in range(len(specs)):
        lines.append(f"    gPs1RestorePilot{idx},")
    lines.extend(["};", "", "#endif"])
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec", type=Path, action="append", dest="specs")
    ap.add_argument("--header", type=Path, default=DEFAULT_HEADER)
    return ap


def main() -> int:
    args = build_parser().parse_args()
    spec_paths = args.specs or DEFAULT_SPECS
    specs = [load_json(path) for path in spec_paths]
    args.header.write_text(build_header(specs), encoding="utf-8")
    print(
        json.dumps(
            {
                "header": str(args.header),
                "specs": [str(path) for path in spec_paths],
                "pilots": [
                    {
                        "ads_name": spec["selected_scene"]["ads_name"],
                        "ads_tag": spec["selected_scene"]["ads_tag"],
                    }
                    for spec in specs
                ],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
