#!/usr/bin/env python3
"""Generate config/ps1/regtest-scenes.txt from the current rollout manifest."""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path


STATUS_MAP = {
    "verified_live": "bringup",
    "live_bringup": "bringup",
    "artifact_ready_unverified": "untested",
    "blocked_entry_path_or_unreliable_route": "blocked",
}

STATUS_ORDER = {
    "bringup": 0,
    "untested": 1,
    "blocked": 2,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--manifest",
        default="docs/ps1/research/generated/restore_rollout_manifest_2026-03-21.json",
        help="Input rollout manifest JSON",
    )
    parser.add_argument(
        "--output",
        default="config/ps1/regtest-scenes.txt",
        help="Output scene list path",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest_path = Path(args.manifest)
    output_path = Path(args.output)

    with manifest_path.open() as f:
        manifest = json.load(f)

    rows = manifest["rows"]
    by_family: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        by_family[row["ads_name"]].append(row)

    lines: list[str] = []
    lines.append("# PS1 Regtest Scene List")
    lines.append("# Generated by scripts/sync-regtest-scenes.py from the current rollout manifest.")
    lines.append("# Format: ADS_NAME TAG SCENE_INDEX STATUS BOOTMODE...")
    lines.append("# STATUS: bringup | blocked | untested")
    lines.append("# BOOTMODE defaults to exact story-scene routes where available.")
    lines.append("#")

    for ads_name in sorted(by_family):
        family_rows = sorted(by_family[ads_name], key=lambda row: row["ads_tag"])
        family_statuses = defaultdict(int)
        for row in family_rows:
            family_statuses[STATUS_MAP.get(row["status"], "untested")] += 1

        summary = ", ".join(
            f"{status}={family_statuses[status]}"
            for status in sorted(family_statuses, key=lambda s: STATUS_ORDER[s])
        )
        lines.append(f"# --- {ads_name} ({summary}) ---")

        ads_stem = ads_name.removesuffix(".ADS")
        for row in family_rows:
            status = STATUS_MAP.get(row["status"], "untested")
            scene_index = row["scene_index"]
            boot_string = f"story scene {scene_index}"
            lines.append(
                f"{ads_stem} {row['ads_tag']} {scene_index} {status} {boot_string}"
            )
        lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines).rstrip() + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
